### ISSUE TITLE
2020.6.6那一次更新是不是导致代码生成器不能用了？

### ISSUE THREAD

**Issue by LiuNing0306** [iamoldli/NetModular.Module.CodeGenerator#10]
我本地运行打开模块创建报403，发布到IIS上没有 显示模块创建？
![image](https://user-images.githubusercontent.com/38337514/84479628-d75db980-acc5-11ea-9179-7a99e477d5f4.png)

**Comment by iamoldli** [comment]
需要重新配置菜单并授权
