### ISSUE TITLE
能不能把项目中的依赖项一起添加进解决方案中，方便阅读

### ISSUE THREAD

**Issue by simplerjiang** [iamoldli/NetModular.Module.CodeGenerator#2]
NetModular.Lib.Cache.MemoryCache
NetModular.Lib.Data.MySql
NetModular.Lib.Data.SQLite
NetModular.Lib.Data.SqlServer
NetModular.Lib.Excel.EPPlus
NetModular.Lib.Host.Web
NetModular.Module.Admin.Web

**Comment by iamoldli** [comment]
模块只包含业务代码，基础框架都是通过nuget安装的，如果想查阅基础库代码，可以到这个仓库里面查看[https://github.com/iamoldli/NetModular](https://github.com/iamoldli/NetModular)里面，如果想调试，可以通过附加进程的方式~
