### ISSUE TITLE
实体管理中的视图模型永远只会显示第一次点击的实体的信息

### ISSUE THREAD

**Issue by xiaosa1944** [iamoldli/NetModular.Module.CodeGenerator#6]
第一次点击一个实体视图模型如下图所示：
![LWF~J{@TRCY(V1)TAQ1KUBR](https://user-images.githubusercontent.com/8485380/76684781-c3180b00-6649-11ea-8e69-511a5629db69.png)
第二点击另一个实体视图模型如下图所示，数据还是第一次点击的
![RBBLJEVCO2S$T28 LQ)$8K7](https://user-images.githubusercontent.com/8485380/76684792-e0e57000-6649-11ea-8b08-bb7d6042b40b.png)
classid还是一样
打开对话框也不会自动加载数据，需要点击查询按钮

**Comment by iamoldli** [comment]
已修复~
